/* Sightline publisher pitch — configuration.
   Everything a pitch variant can change lives here; sightline-pitch.html reads it at load.
   Select a publisher with ?to=<key> (default: PITCH.defaultPublisher). Unknown key → the
   publisher-specific section is hidden and the page reads as a general pitch. */
window.PITCH = {
  defaultPublisher: 'rawfury',

  /* Links. Empty string = not available yet: the page then shows the action as "on request" (mailto). */
  links: {
    trailer: '#trailer',                         /* in-page trailer (pitch/trailer.mp4) */
    build:   '',                                 /* PUBLISHER_BUILD_URL — Sightline_Publisher_macOS.zip (131 MB, too big for this host: use a Drive/Dropbox/R2 link) */
    pdf:     'pitch/Sightline-Pitch.pdf',        /* generated by pitch/make-pdf.js from this page's print stylesheet */
    contact: 'mailto:yoni@yumloop.net?subject=Sightline'
  },

  launch: 'Q4 2026',                             /* target launch, shown in "When will you be there?" — flexible with publishing strategy */

  /* Publisher-specific "Why you?" copy. Keys are what ?to= accepts. */
  publishers: {
    rawfury: {
      name: 'Raw Fury',
      why: [
        'I’m approaching Raw Fury because of the breadth of mechanically distinctive independent games you’ve successfully helped bring to market.',
        'Sightline isn’t a game whose value comes from enormous production scope. Its strength is a simple central idea that creates significantly more depth than it initially appears to.',
        'I’m looking for a publisher that sees that simplicity as a strength and can help communicate it to a much larger audience.'
      ]
    },
    snapbreak:  { name: 'Snapbreak',  why: [ 'PLACEHOLDER — write the Snapbreak-specific reasoning here (2–3 short paragraphs).' ] },
    whitethorn: { name: 'Whitethorn', why: [ 'PLACEHOLDER — write the Whitethorn-specific reasoning here (2–3 short paragraphs).' ] },
    akupara:    { name: 'Akupara',    why: [ 'PLACEHOLDER — write the Akupara-specific reasoning here (2–3 short paragraphs).' ] }
  }
};
