/* Sightline publisher pitch — configuration.
   Everything a pitch variant can change lives here; sightline-pitch.html reads it at load.
   Select a publisher with ?to=<key>. With no key (the default link) the page names nobody: the
   "Why you?" section shows its generic copy. A key swaps in that publisher's name and paragraphs. */
window.PITCH = {
  defaultPublisher: '',                        /* '' = the generic, publisher-neutral page (what the shared link shows). A key here or ?to=<key> swaps in a named 'why' section. */

  /* Links. Empty string = not available yet: the page then shows the action as "on request" (mailto). */
  links: {
    trailer: '#trailer',                         /* in-page trailer (pitch/trailer.mp4) */
    build:        'https://github.com/PegaXing/yumloop-site/releases/download/build-0.10.361/Sightline_Publisher_macOS.zip',    /* notarized universal (Apple Silicon + Intel) macOS app, 223 MB (GitHub release asset: the site itself cannot host files this size) */
    buildWindows: 'https://github.com/PegaXing/yumloop-site/releases/download/build-0.10.361/Sightline_Publisher_Windows.zip',  /* Windows x64, 154 MB, unsigned (SmartScreen once); QA-passed on a Windows runner via sightline/.github/workflows/publisher-windows-qa.yml */
    pdf:     'pitch/Sightline-Pitch.pdf',        /* generated by pitch/make-pdf.js from this page's print stylesheet */
    contact: 'mailto:yoni@yumloop.net?subject=Sightline'
  },

  launch: 'Q4 2026',
  budget: '',                                  /* development budget line for the scout panel; '' keeps the default "complete and self-funded" wording */
                             /* target launch, shown in "When will you be there?" — flexible with publishing strategy */

  /* Publisher-specific "Why you?" copy. Keys are what ?to= accepts. */
  publishers: {
    rawfury: {
      name: 'Raw Fury',
      why: [
        'I’m approaching Raw Fury because of the breadth of mechanically distinctive independent games you’ve successfully helped bring to market.',
        'Sightline isn’t a game whose value comes from enormous production scope. Its strength is a simple central idea that creates significantly more depth than it initially appears to.',
        'I’m looking for a publisher that sees that simplicity as a strength and can help communicate it to a much larger audience.'
      ]
    },
    snapbreak:  { name: 'Snapbreak',  why: [ 'PLACEHOLDER — write the Snapbreak-specific reasoning here (2–3 short paragraphs).' ] },
    whitethorn: { name: 'Whitethorn', why: [ 'PLACEHOLDER — write the Whitethorn-specific reasoning here (2–3 short paragraphs).' ] },
    akupara:    { name: 'Akupara',    why: [ 'PLACEHOLDER — write the Akupara-specific reasoning here (2–3 short paragraphs).' ] }
  }
};
